# Generated by Django 2.2.24 on 2022-09-05 09:38

from django.db import migrations


def add_new_building_status(apps, schema_editor):
    """Добавить квартире статус новостройки"""
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_buildings=True)


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte= 2015).update(new_building=None)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(
            add_new_building_status,
            move_backward,
        ),
    ]
