# Generated by Django 2.2.24 on 2022-09-05 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(related_name='liked_apartments', to=settings.AUTH_USER_MODEL, verbose_name='пользователи, поставившие лайки'),
        ),
    ]
